set_global_assignment -name STRATIX_DEVICE_IO_STANDARD "3.3-V LVCMOS"                                                                                                                

set_location_assignment PIN_65 -to audiol
set_location_assignment PIN_80 -to audior
set_location_assignment PIN_55 -to clk_27[1]
set_location_assignment PIN_54 -to clk_27[0]
set_location_assignment PIN_32 -to dram_a[12]
set_location_assignment PIN_30 -to dram_a[11]
set_location_assignment PIN_50 -to dram_a[10]
set_location_assignment PIN_28 -to dram_a[9]
set_location_assignment PIN_11 -to dram_a[8]
set_location_assignment PIN_10 -to dram_a[7]
set_location_assignment PIN_8 -to dram_a[6]
set_location_assignment PIN_6 -to dram_a[5]
set_location_assignment PIN_4 -to dram_a[4]
set_location_assignment PIN_39 -to dram_a[3]
set_location_assignment PIN_42 -to dram_a[2]
set_location_assignment PIN_44 -to dram_a[1]
set_location_assignment PIN_49 -to dram_a[0]
set_location_assignment PIN_51 -to dram_ba[1]
set_location_assignment PIN_58 -to dram_ba[0]
set_location_assignment PIN_64 -to dram_cas_n
set_location_assignment PIN_43 -to dram_clk
set_location_assignment PIN_59 -to dram_cs_n
set_location_assignment PIN_60 -to dram_ras_n
set_location_assignment PIN_66 -to dram_we_n
set_location_assignment PIN_104 -to dram_dq[15]
set_location_assignment PIN_103 -to dram_dq[14]
set_location_assignment PIN_101 -to dram_dq[13]
set_location_assignment PIN_100 -to dram_dq[12]
set_location_assignment PIN_99 -to dram_dq[11]
set_location_assignment PIN_98 -to dram_dq[10]
set_location_assignment PIN_87 -to dram_dq[9]
set_location_assignment PIN_86 -to dram_dq[8]
set_location_assignment PIN_68 -to dram_dq[7]
set_location_assignment PIN_69 -to dram_dq[6]
set_location_assignment PIN_71 -to dram_dq[5]
set_location_assignment PIN_72 -to dram_dq[4]
set_location_assignment PIN_76 -to dram_dq[3]
set_location_assignment PIN_77 -to dram_dq[2]
set_location_assignment PIN_79 -to dram_dq[1]
set_location_assignment PIN_83 -to dram_dq[0]
set_location_assignment PIN_85 -to dram_dqm[1]
set_location_assignment PIN_67 -to dram_dqm[0]
set_location_assignment PIN_31 -to uart_rx
set_location_assignment PIN_46 -to uart_tx
set_location_assignment PIN_7 -to led_yellow_n
set_location_assignment PIN_133 -to vga_blue[5]
set_location_assignment PIN_132 -to vga_blue[4]
set_location_assignment PIN_125 -to vga_blue[3]
set_location_assignment PIN_121 -to vga_blue[2]
set_location_assignment PIN_120 -to vga_blue[1]
set_location_assignment PIN_115 -to vga_blue[0]
set_location_assignment PIN_114 -to vga_green[5]
set_location_assignment PIN_113 -to vga_green[4]
set_location_assignment PIN_112 -to vga_green[3]
set_location_assignment PIN_111 -to vga_green[2]
set_location_assignment PIN_110 -to vga_green[1]
set_location_assignment PIN_106 -to vga_green[0]
set_location_assignment PIN_119 -to vga_hsync
set_location_assignment PIN_144 -to vga_red[5]
set_location_assignment PIN_143 -to vga_red[4]
set_location_assignment PIN_142 -to vga_red[3]
set_location_assignment PIN_141 -to vga_red[2]
set_location_assignment PIN_137 -to vga_red[1]
set_location_assignment PIN_135 -to vga_red[0]
set_location_assignment PIN_136 -to vga_vsync
set_location_assignment PIN_89 -to reset_n
set_location_assignment PIN_33 -to test_point_tp1
set_location_assignment PIN_105 -to spi_do                                                                                                                                           
set_location_assignment PIN_88 -to spi_di                                                                                                                                            
set_location_assignment PIN_126 -to spi_sck                                                                                                                                          
set_location_assignment PIN_127 -to spi_ss2                                                                                                                                          
set_location_assignment PIN_91 -to spi_ss3                                                                                                                                           
set_location_assignment PIN_90 -to spi_ss4   
set_location_assignment PIN_13 -to conf_data0                                                                                                                                        

set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to vga_*                                                                                                       
