onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider testbench
add wave -noupdate /top_mist_sdram_tb/simulation_run
add wave -noupdate /top_mist_sdram_tb/tb_clk27
add wave -noupdate /top_mist_sdram_tb/tb_led_yellow
add wave -noupdate /top_mist_sdram_tb/tb_test_point_tp1
add wave -noupdate -divider reset
add wave -noupdate /top_mist_sdram_tb/top_mist_i0/sys_reset_n
add wave -noupdate -divider cpu
add wave -noupdate /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/boot_state
add wave -noupdate -radix hexadecimal -childformat {{/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(15) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(14) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(13) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(12) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(11) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(10) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(9) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(8) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(7) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(6) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(5) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(4) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(3) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(2) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(1) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(0) -radix hexadecimal}} -subitemconfig {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(15) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(14) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(13) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(12) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(11) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(10) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(9) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(8) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(7) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(6) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(5) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(4) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(3) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(2) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(1) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A(0) {-height 16 -radix hexadecimal}} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/A
add wave -noupdate -radix hexadecimal -childformat {{/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(7) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(6) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(5) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(4) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(3) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(2) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(1) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(0) -radix hexadecimal}} -subitemconfig {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(7) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(6) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(5) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(4) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(3) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(2) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(1) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI(0) {-height 16 -radix hexadecimal}} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DI
add wave -noupdate -radix hexadecimal /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/DO
add wave -noupdate /top_mist_sdram_tb/top_mist_i0/clk_2MHz_4MHz
add wave -noupdate /top_mist_sdram_tb/top_mist_i0/cpu_clk
add wave -noupdate -divider SDRAM
add wave -noupdate -radix hexadecimal -childformat {{/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(7) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(6) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(5) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(4) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(3) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(2) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(1) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(0) -radix hexadecimal}} -subitemconfig {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(7) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(6) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(5) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(4) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(3) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(2) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(1) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC(0) {-height 16 -radix hexadecimal}} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/T80_1/u0/ACC
add wave -noupdate -radix unsigned /top_mist_sdram_tb/top_mist_i0/ram/sdram_controller_inst/reset
add wave -noupdate -radix unsigned -childformat {{/top_mist_sdram_tb/top_mist_i0/ram/sdram_controller_inst/q(2) -radix unsigned} {/top_mist_sdram_tb/top_mist_i0/ram/sdram_controller_inst/q(1) -radix unsigned} {/top_mist_sdram_tb/top_mist_i0/ram/sdram_controller_inst/q(0) -radix unsigned}} -subitemconfig {/top_mist_sdram_tb/top_mist_i0/ram/sdram_controller_inst/q(2) {-height 16 -radix unsigned} /top_mist_sdram_tb/top_mist_i0/ram/sdram_controller_inst/q(1) {-height 16 -radix unsigned} /top_mist_sdram_tb/top_mist_i0/ram/sdram_controller_inst/q(0) {-height 16 -radix unsigned}} /top_mist_sdram_tb/top_mist_i0/ram/sdram_controller_inst/q
add wave -noupdate -radix hexadecimal -childformat {{/top_mist_sdram_tb/top_mist_i0/sdram_dout(7) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/sdram_dout(6) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/sdram_dout(5) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/sdram_dout(4) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/sdram_dout(3) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/sdram_dout(2) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/sdram_dout(1) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/sdram_dout(0) -radix hexadecimal}} -subitemconfig {/top_mist_sdram_tb/top_mist_i0/sdram_dout(7) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/sdram_dout(6) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/sdram_dout(5) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/sdram_dout(4) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/sdram_dout(3) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/sdram_dout(2) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/sdram_dout(1) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/sdram_dout(0) {-height 16 -radix hexadecimal}} /top_mist_sdram_tb/top_mist_i0/sdram_dout
add wave -noupdate -radix hexadecimal -childformat {{/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(7) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(6) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(5) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(4) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(3) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(2) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(1) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(0) -radix hexadecimal}} -subitemconfig {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(7) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(6) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(5) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(4) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(3) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(2) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(1) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in(0) {-height 16 -radix hexadecimal}} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/ramData_in
add wave -noupdate -radix hexadecimal -childformat {{/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(7) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(6) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(5) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(4) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(3) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(2) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(1) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(0) -radix hexadecimal}} -subitemconfig {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(7) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(6) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(5) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(4) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(3) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(2) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(1) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM(0) {-height 16 -radix hexadecimal}} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data4RAM
add wave -noupdate /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/sel_rom_n
add wave -noupdate /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/sel_vram_n
add wave -noupdate /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/sel_dram_n
add wave -noupdate /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/sel_sram_n
add wave -noupdate -radix hexadecimal /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/data2cpu
add wave -noupdate -radix hexadecimal -childformat {{/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(15) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(14) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(13) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(12) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(11) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(10) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(9) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(8) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(7) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(6) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(5) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(4) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(3) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(2) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(1) -radix hexadecimal} {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(0) -radix hexadecimal}} -subitemconfig {/top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(15) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(14) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(13) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(12) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(11) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(10) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(9) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(8) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(7) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(6) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(5) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(4) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(3) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(2) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(1) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr(0) {-height 16 -radix hexadecimal}} /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/addr
add wave -noupdate /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/mreq_n
add wave -noupdate /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/IOREQ_n
add wave -noupdate /top_mist_sdram_tb/top_mist_i0/redz0mb1e_1/RFSH_n
add wave -noupdate /top_mist_sdram_tb/top_mist_i0/ram/sdram_controller_inst/state
add wave -noupdate /top_mist_sdram_tb/top_mist_i0/ram/sdram_controller_inst/sd_cmd
add wave -noupdate -expand -group dRAM /top_mist_sdram_tb/tb_dram_clk
add wave -noupdate -expand -group dRAM -radix hexadecimal /top_mist_sdram_tb/tb_dram_a
add wave -noupdate -expand -group dRAM /top_mist_sdram_tb/tb_dram_ba
add wave -noupdate -expand -group dRAM /top_mist_sdram_tb/tb_dram_cs_n
add wave -noupdate -expand -group dRAM -radix hexadecimal -childformat {{/top_mist_sdram_tb/tb_dram_dq(15) -radix hexadecimal} {/top_mist_sdram_tb/tb_dram_dq(14) -radix hexadecimal} {/top_mist_sdram_tb/tb_dram_dq(13) -radix hexadecimal} {/top_mist_sdram_tb/tb_dram_dq(12) -radix hexadecimal} {/top_mist_sdram_tb/tb_dram_dq(11) -radix hexadecimal} {/top_mist_sdram_tb/tb_dram_dq(10) -radix hexadecimal} {/top_mist_sdram_tb/tb_dram_dq(9) -radix hexadecimal} {/top_mist_sdram_tb/tb_dram_dq(8) -radix hexadecimal} {/top_mist_sdram_tb/tb_dram_dq(7) -radix hexadecimal} {/top_mist_sdram_tb/tb_dram_dq(6) -radix hexadecimal} {/top_mist_sdram_tb/tb_dram_dq(5) -radix hexadecimal} {/top_mist_sdram_tb/tb_dram_dq(4) -radix hexadecimal} {/top_mist_sdram_tb/tb_dram_dq(3) -radix hexadecimal} {/top_mist_sdram_tb/tb_dram_dq(2) -radix hexadecimal} {/top_mist_sdram_tb/tb_dram_dq(1) -radix hexadecimal} {/top_mist_sdram_tb/tb_dram_dq(0) -radix hexadecimal}} -subitemconfig {/top_mist_sdram_tb/tb_dram_dq(15) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/tb_dram_dq(14) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/tb_dram_dq(13) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/tb_dram_dq(12) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/tb_dram_dq(11) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/tb_dram_dq(10) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/tb_dram_dq(9) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/tb_dram_dq(8) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/tb_dram_dq(7) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/tb_dram_dq(6) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/tb_dram_dq(5) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/tb_dram_dq(4) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/tb_dram_dq(3) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/tb_dram_dq(2) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/tb_dram_dq(1) {-height 16 -radix hexadecimal} /top_mist_sdram_tb/tb_dram_dq(0) {-height 16 -radix hexadecimal}} /top_mist_sdram_tb/tb_dram_dq
add wave -noupdate -expand -group dRAM /top_mist_sdram_tb/tb_dram_ras_n
add wave -noupdate -expand -group dRAM /top_mist_sdram_tb/tb_dram_cas_n
add wave -noupdate -expand -group dRAM /top_mist_sdram_tb/tb_dram_we_n
add wave -noupdate /top_mist_sdram_tb/sdram_i0/Main/statebank(0)
add wave -noupdate -divider io
add wave -noupdate -group VGA /top_mist_sdram_tb/top_mist_i0/vga_blue
add wave -noupdate -group VGA /top_mist_sdram_tb/top_mist_i0/vga_green
add wave -noupdate -group VGA /top_mist_sdram_tb/top_mist_i0/vga_red
add wave -noupdate -group VGA /top_mist_sdram_tb/top_mist_i0/vga_hsync
add wave -noupdate -group VGA /top_mist_sdram_tb/top_mist_i0/vga_vsync
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 3} {202806769 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits us
update
WaveRestoreZoom {201554975 ps} {204395179 ps}
